sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tomweidner103/fib-test-react -f ./client/Dockerfile.dev ./client
  # more projects 

script:
  - docker run -e CI=true tomweidner103/fib-test-react npm test
  # more projects 

after_success:
  - docker build -t tomweidner103/fib-client ./client
  - docker build -t tomweidner103/fib-nginx ./nginx
  - docker build -t tomweidner103/fib-server ./server
  - docker build -t tomweidner103/fib-worker ./worker
# login to docker cli (docker hub)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to dokcer hub
  - docker push tomweidner103/fib-client
  - docker push tomweidner103/fib-nginx
  - docker push tomweidner103/fib-server
  - docker push tomweidner103/fib-worker

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-741024833687"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
