# This is for setting up the server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: api
          image: tomweidner103/fib-server
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            # this also needs to be changed in postgres delpoyment
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  # this needs to be assembled in kubernetes in gcloud
                  key: POSTGRES_PASSWORD # key from key/value pair we made
                  name: pgpassword # name of password we created with kubectl command
          ports:
            - containerPort: 5000
